apiVersion: v1
kind: Service
metadata:
  name: customer-order-api
spec:
  selector:
    app: customer-order-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
